project_id = "akfvitjbmtrbtosfwmwj"

[functions.invite-to-plan]
verify_jwt = true

[functions.import-report-data]
verify_jwt = false

[functions.seed-test-plans]
verify_jwt = false

[functions.admin-operations]
verify_jwt = false

[functions.invite-environment-member]
verify_jwt = false

[functions.send-resource-notification]
verify_jwt = false
